### PR TITLE
Bug fixes 1

### LINKED ISSUE #67: Location constraint doesn't handle large text in activity cell & view activity
screen shot 2019-02-23 at 7 17 17 pm
screen shot 2019-02-23 at 7 17 24 pm

### LINKED ISSUE #73: Daterange text in view activity cell is constrained poorly
it cuts off after like two words of "tomorrow throuh..." (see screenshot)
screen shot 2019-02-24 at 7 35 46 pm

cc @lukemeierj or @gyurisic

### LINKED ISSUE #77: Cancel button is red on pick topics screen
should be normal blue color

### PR DESCRIPTION
**Pull request by lukemeierj**
Resolves #77 by simply making the cancel button in `Pick Topics` blue.

To test:
1. Is the cancel button in Pick Topics blue? Cool.

Resolves #73:
 * changing constraints
 * shortening date strings if the title is long
 * shorting date strings if the date string is long

To test:
1. Create some activities, especially ones dealing with the next few days 
   * Some with long titles, some with short titles
2. None of the date strings should have ellipses, and should not be truncated
3. Long titles can be truncated w/ ellipses 

screen shot 2019-03-01 at 2 23 34 pm
screen shot 2019-03-01 at 2 21 41 pm

Resolves #67:
* Adding some constraints

To test:
1. Create an activity with a long location string (you can modify it in Firebase console if that's easier)
2. All the photos in the Tableview should appear un-occluded 
3. The long title may have ellipses to the right
4. In the view activity screen, only the location should be truncated with ellipses 
screen shot 2019-03-01 at 2 39 03 pm
Or not cut off, if the screen is big enough
screen shot 2019-03-01 at 2 29 40 pm

Test all these on at least two device sizes.

### CODE REVIEW

**Comment by lukemeierj** [comment]
Note: Since we aren't using nibs for the ActivityCell, the new ActivityCell from the `Topics.storyboard` will need to be copied into every other place the activity cell is used.

This applies to @gyurisic 's work and #81

**Comment by noahtallen** [comment]
we should really use a nib for that cell... it will be used in at least 3 places

File: Buddies/Activities/ActivityTableVC.swift [hunk 1]
```diff
@@ -149,8 +149,17 @@ class ActivityTableVC: UITableViewController, FilterSearchBarDelegate {
...
+        let pixelsPerChar: CGFloat = 10.0
+        
+        let charsFitInCell = Int(cell.frame.width/pixelsPerChar)
+        
+        let locStrLength = max(15, charsFitInCell - activity.title.count)
+        
+        let locStr = dateRange.rangePhrase(relativeTo: Date(), tryShorteningIfLongerThan: locStrLength)
         
-        cell.dateLabel.text = dateRange.rangePhrase(relativeTo: Date()).capitalized
+        cell.dateLabel.text = locStr.capitalized
```
Comment (noahtallen) [inline Buddies/Activities/ActivityTableVC.swift:162]: Interesting. Is there any reason plain constraints wouldn't work to solve this problem?? Though I guess you need to know how long the string is

**Review by noahtallen — APPROVED** [review]
Looks dope! Thanks for fixing these!

File: Buddies/Activities/ActivityTableVC.swift (hunk 1 above)
Comment (lukemeierj) [reply Buddies/Activities/ActivityTableVC.swift:162]: It was kind of a preference I ran with.  I want to support at least 15 characters of a date string at a minimum, but when more space allows, I like the longer string.  That's why I change it based on the title/screen size.
